//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointsOfInterest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PointsOfInterestContext : DbContext
    {
        public PointsOfInterestContext()
            : base("name=PointsOfInterestContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Museum> Museums { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Rates_Users_Hotels> Rates_Users_Hotels { get; set; }
        public virtual DbSet<Rates_Users_Museums> Rates_Users_Museums { get; set; }
        public virtual DbSet<Rates_Users_Places> Rates_Users_Places { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
